#ifndef __VERSION_INFO_CONSTANTS_H_
#define __VERSION_INFO_CONSTANTS_H_

#pragma once

#define VERSION_INFO_STR "10.0.1999"

#define VER_FILEVERSION 10,0,1999
#define VER_FILEVERSION_STR "10.0.1999"

#endif // __VERSION_INFO_CONSTANTS_H_
